# Generated by Django 4.2.7 on 2026-02-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quarterly Kyathi Bidding/Applications', max_length=200)),
                ('month', models.PositiveIntegerField(choices=[(4, 'April'), (8, 'August'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='EventWinnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_eventwinnerhistory',
                'indexes': [models.Index(fields=['member'], name='events_even_member__440243_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_venue', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event')),
            ],
            options={
                'db_table': 'events_eventapplication',
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_828f37_idx'), models.Index(fields=['applicant', 'status'], name='events_even_applica_a1b551_idx')],
                'unique_together': {('event', 'applicant')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['year', 'month'], name='events_even_year_c31542_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_completed'], name='events_even_is_comp_cce944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('month', 'year')},
        ),
    ]
