# Generated by Django 4.2.7 on 2026-02-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('registration_fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_dropped', models.BooleanField(default=False)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members_memberprofile',
                'indexes': [models.Index(fields=['user'], name='members_mem_user_id_fc5602_idx'), models.Index(fields=['is_dropped'], name='members_mem_is_drop_38708c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contribution_type', models.CharField(choices=[('monthly', 'Monthly Contribution'), ('quarterly', 'Quarterly Contribution'), ('registration', 'Registration Fee'), ('meeting', 'Meeting Facilitation'), ('custom', 'Custom Contribution')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('deadline_day', models.PositiveIntegerField(blank=True, help_text='Day of month for deadline', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members_contributiontype',
                'indexes': [models.Index(fields=['contribution_type', 'is_active'], name='members_con_contrib_b5ceab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('paid_late', 'Paid with Late'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.contributiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_contribution',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash')], max_length=10)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('callback_received', models.BooleanField(default=False)),
                ('callback_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_late_payment', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_paymenttransaction',
                'indexes': [models.Index(fields=['user', 'status'], name='members_pay_user_id_503f3a_idx'), models.Index(fields=['idempotency_key'], name='members_pay_idempot_71703d_idx'), models.Index(fields=['merchant_request_id'], name='members_pay_merchan_c7a382_idx'), models.Index(fields=['checkout_request_id'], name='members_pay_checkou_cb26cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.contribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_debt',
                'indexes': [models.Index(fields=['user', 'is_cleared'], name='members_deb_user_id_8d0c84_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['user', 'status'], name='members_con_user_id_cd0d10_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['user', 'year', 'month'], name='members_con_user_id_72c1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contribution_type', 'status'], name='members_con_contrib_7ecba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('user', 'contribution_type', 'year', 'month', 'quarter')},
        ),
    ]
