# Generated by Django 4.2.7 on 2026-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_cashpaymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('paid_late', 'Paid with Late'), ('partial', 'Partial'), ('waiting_approval', 'Waiting Approval'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
