# Generated by Django 4.2.7 on 2026-03-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_contribution_status'),
    ]

    operations = [
    ]
