# Generated by Django 6.0.7 on 2026-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_add_rejected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('paid_late', 'Paid with Late'), ('partial', 'Partial'), ('waiting_approval', 'Waiting Approval'), ('waiting_reapproval', 'Waiting Reapproval'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
