# Generated by Django 6.0.7 on 2026-07-17 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('admin_login_success', 'Admin Login Success'), ('admin_login_failed', 'Admin Login Failed'), ('admin_logout', 'Admin Logout'), ('logout', 'Logout'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_success', 'Password Reset Success'), ('reset_code_verified', 'Reset Code Verified'), ('reset_code_invalid', 'Reset Code Invalid'), ('password_reset_expired', 'Password Reset Expired'), ('password_changed', 'Password Changed'), ('initial_password_set', 'Initial Password Set'), ('admin_initial_password_set', 'Admin Initial Password Set'), ('admin_password_reset_requested', 'Admin Password Reset Requested'), ('admin_reset_code_verified', 'Admin Reset Code Verified'), ('admin_reset_code_invalid', 'Admin Reset Code Invalid'), ('admin_password_reset_success', 'Admin Password Reset Success'), ('admin_password_reset_expired', 'Admin Password Reset Expired'), ('member_application_submitted', 'Member Application Submitted'), ('member_application_approved', 'Member Application Approved'), ('member_application_rejected', 'Member Application Rejected'), ('member_application_on_hold', 'Member Application On Hold'), ('phone_updated', 'Phone Updated'), ('profile_picture_uploaded', 'Profile Picture Uploaded'), ('profile_picture_removed', 'Profile Picture Removed'), ('member_created_by_admin', 'Member Created By Admin'), ('member_updated_by_admin', 'Member Updated By Admin'), ('member_deactivated_by_admin', 'Member Deactivated By Admin'), ('session_expired', 'Session Expired'), ('rate_limit_exceeded', 'Rate Limit Exceeded')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('user_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_securitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_se_event_t_e02baa_idx'), models.Index(fields=['ip_address'], name='accounts_se_ip_addr_935ef8_idx'), models.Index(fields=['user_identifier'], name='accounts_se_user_id_f9fd53_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('agreed_to_privacy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_memberapplication',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='accounts_me_email_d68c8e_idx'), models.Index(fields=['id_number', 'status'], name='accounts_me_id_numb_b08084_idx'), models.Index(fields=['status', 'created_at'], name='accounts_me_status_d5dd8a_idx')],
            },
        ),
    ]
